### ISSUE TITLE
Fussy centering of input field with probability to the right

### ISSUE THREAD

**Issue by dreeves** [bsoule/Expectorant#20]
I wanted to have the input field always perfectly centered, with the parsed probability label to the right if it fits, and otherwise wrapped to the next line, flush left with the input box.

I made a Replit bounty for this like so:

See the input field at https://expectorant.dreev.repl.co/? And see how it has a small dynamic label to the right of it? I'd like the input field to be centered and the label to be to the right of it, not influencing the centering. (Or if no room to the right, wrap it to the next line, flushed left -- like it currently does.)

It's basically what https://stackoverflow.com/questions/48084753/how-to-center-inputs-in-a-form-with-labels-on-the-same-line is asking for but I tried the proposed solutions and they didn't work. Maybe because I'm also doing fussy things with max width of the input field and I want to the label to wrap to the next line if the browser width is too narrow.

To spell this out:

1. take the original version of the app which you can see at http://expectorant.yootl.es/
2. totally remove (comment out) the label element that displays the "p=__" (you can see a version like this at http://expectorant.glitch.me/ )
3. note how the input field behaves: always perfectly centered, uses up 95% of the browser width unless that makes the input field more than 390px where the input field width maxes out.
4. bring back the label and have it appear to the right of the input field if there's room to the right, otherwise put it on the next line.
5. but the behavior in step 3 should stay exactly the same despite the label being visible now.

**Comment by dreeves** [comment]
Here are aborted attempts at this from Bee and a couple different Replit bounty hunters:

```css
/* Breakpoint for small screens
 * NOTE: the standard for small screens is max-width: 600px according to 
 * w3schools, but because of some fussing with the input width, and the 
 * placeholder text there, and getting everything neatly centered etc,
 * I picked a slightly smaller width of 550px for the small screen breakpoint.
 */
@media only screen and (max-width: 550) {
  body {
    background-color:aliceblue; /* for debugging: be blue when narrow */
  }
  input {
    width: 60%;
  }
}

.input-wrap {
  padding: 0;
  margin: auto;
  margin-bottom: 1em;
  text-align: center;
  position: relative;
}
label {
  /* position: absolute; */
  padding-left: 0.5rem;
  top: 10px;
  bottom: 10px;
  box-sizing: border-box; 
}

@media only screen and (min-width: 1080px) {
  .texty {
    margin-left: 2vw;
    margin-right: 2vw;
    text-align: center;
  }
  
  p {
    max-width: 800px;
  }

  #instructions {
  text-align: left !important;
  margin-left: calc((50% - 800px) / 2);
  margin-right: calc((50% - 800px) / 2);
  /*
  left: 30vw;
  position: fixed;
  */
  }
  
  summary {
    padding-bottom: .5vh;
  }
}
```

```javascript
// Courtesy of Abhijit for centering only the input element, not centering the
// combination of the input and the "p=0.123" label.
function fussyCenter() {
  let ww = window.innerWidth
  let iw = document.querySelector(".input-wrap input").offsetWidth
  let lw = document.querySelector(".input-wrap label").offsetWidth
  //console.log(lw, (ww-iw)/2)
  lw > ((ww-iw)/2) ? 
    document.querySelector(".input-wrap").classList.add("noncetag") : 
    document.querySelector(".input-wrap").classList.remove("noncetag")
}
fussyCenter()
document.querySelector(".input-wrap label")
        .addEventListener("DOMSubtreeModified", fussyCenter)
```
